export type TCar = {
  _id: string;
  name: string;
  type: string;
  pricePerHour: number;
  status: string;
  engineType: string;
  description: string;
  isDeleted: boolean;
  features: string[];
  images: string[];
  brand: string;
  model: string;
  fuelType: string;
  transmission: string;
  seatingCapacity: number;
  color: string;
  noOfDoors: number;
  year: number;
  currentLocation?: string;
};
